version: '3.8'
services:
  mysql_test:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: abcBolinhas12345
      MYSQL_DATABASE: db_academia_do_ze
      MYSQL_USER: test
      MYSQL_PASSWORD: testpwd
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
